# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my',
            name='gif_name',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
