# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luda', '0002_my_gif_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my',
            name='gif_name',
            field=models.CharField(default='', max_length=9999, null=True),
        ),
    ]
