# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luda', '0003_auto_20171201_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif_name', models.CharField(default='', max_length=9999)),
            ],
        ),
        migrations.RemoveField(
            model_name='my',
            name='gif_name',
        ),
    ]
