# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='content',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='filtered_image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='source',
            field=models.CharField(default='aa', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='text',
            field=models.CharField(default='text', max_length=500),
            preserve_default=False,
        ),
    ]
