# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170302_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='end',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='start',
            field=models.CharField(default='2', max_length=500),
            preserve_default=False,
        ),
    ]
