# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170302_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='end',
            field=models.CharField(default='5', max_length=500),
        ),
        migrations.AlterField(
            model_name='photo',
            name='start',
            field=models.CharField(default='1', max_length=500),
        ),
    ]
