# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='capture',
            name='src',
        ),
    ]
