# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20170225_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='lock',
            field=models.CharField(default='on', max_length=100),
        ),
    ]
