# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20170228_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv', models.CharField(choices=[('produce101', '프로듀스 101'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=50)),
                ('num', models.CharField(default='1', max_length=100)),
                ('src', models.CharField(max_length=1024)),
            ],
        ),
    ]
