# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_tv_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='tv_choice',
            name='src',
        ),
    ]
