# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20170311_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_choice',
            name='num',
            field=models.CharField(default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='tv_choice',
            name='tv',
            field=models.CharField(choices=[('produce101', '프로듀스 101'), ('behind', '프로듀스 101 비하인드'), ('standby', '스탠바이 아이오아이'), ('snl', 'SNL KOREA 시즌7'), ('taxi', '현장토크쇼 TAXI'), ('sin3', '신서유기3'), ('sin4', '신서유기4'), ('goblin', '도깨비'), ('food3_sea_1', '삼시세끼 어촌편 1'), ('food3_sea_2', '삼시세끼 어촌편 2'), ('high_rap', '고등래퍼'), ('life_', '인생술집'), ('genious_2', '더 지니어스2 - 룰 브레이커'), ('genious_3', '더 지니어스3 - 블랙 가넷'), ('genious_4', '더 지니어스4 - 그랜드 파이널'), ('yoon', '윤식당'), ('ddl', "Dodaeng's Diary in LA")], default='green', max_length=50),
        ),
    ]
