# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_rank_daum_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='melon_rank',
            field=models.CharField(default=' ', max_length=1024),
        ),
        migrations.AlterField(
            model_name='rank',
            name='daum_rank',
            field=models.CharField(default=' ', max_length=1024),
        ),
        migrations.AlterField(
            model_name='rank',
            name='naver_rank',
            field=models.CharField(default=' ', max_length=1024),
        ),
    ]
