# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20170228_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='melontime',
            field=models.CharField(default=' ', max_length=1024),
        ),
    ]
