# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
