# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_mydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='page',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
